/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as RepositoriesNewRouteImport } from './routes/repositories/new'
import { Route as ScannersIndexRouteImport } from './routes/scanners/index'
import { Route as ScansScanIdRouteImport } from './routes/scans/$scanId'
import { Route as RepositoriesRepositoryIdIndexRouteImport } from './routes/repositories/$repositoryId/index'
import { Route as RepositoriesRepositoryIdEditRouteImport } from './routes/repositories/$repositoryId/edit'
import { Route as RepositoriesRepositoryIdKnowledgeRouteImport } from './routes/repositories/$repositoryId/knowledge'
import { Route as RepositoriesRepositoryIdScannersScannerIdRouteImport } from './routes/repositories/$repositoryId/scanners/$scannerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesNewRoute = RepositoriesNewRouteImport.update({
  id: '/repositories/new',
  path: '/repositories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannersIndexRoute = ScannersIndexRouteImport.update({
  id: '/scanners/',
  path: '/scanners/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansScanIdRoute = ScansScanIdRouteImport.update({
  id: '/scans/$scanId',
  path: '/scans/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRepositoryIdIndexRoute =
  RepositoriesRepositoryIdIndexRouteImport.update({
    id: '/repositories/$repositoryId/',
    path: '/repositories/$repositoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoriesRepositoryIdEditRoute =
  RepositoriesRepositoryIdEditRouteImport.update({
    id: '/repositories/$repositoryId/edit',
    path: '/repositories/$repositoryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoriesRepositoryIdKnowledgeRoute =
  RepositoriesRepositoryIdKnowledgeRouteImport.update({
    id: '/repositories/$repositoryId/knowledge',
    path: '/repositories/$repositoryId/knowledge',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoriesRepositoryIdScannersScannerIdRoute =
  RepositoriesRepositoryIdScannersScannerIdRouteImport.update({
    id: '/repositories/$repositoryId/scanners/$scannerId',
    path: '/repositories/$repositoryId/scanners/$scannerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scanners/': typeof ScannersIndexRoute
  '/repositories/$repositoryId/edit': typeof RepositoriesRepositoryIdEditRoute
  '/repositories/$repositoryId/knowledge': typeof RepositoriesRepositoryIdKnowledgeRoute
  '/repositories/$repositoryId/': typeof RepositoriesRepositoryIdIndexRoute
  '/repositories/$repositoryId/scanners/$scannerId': typeof RepositoriesRepositoryIdScannersScannerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scanners': typeof ScannersIndexRoute
  '/repositories/$repositoryId/edit': typeof RepositoriesRepositoryIdEditRoute
  '/repositories/$repositoryId/knowledge': typeof RepositoriesRepositoryIdKnowledgeRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdIndexRoute
  '/repositories/$repositoryId/scanners/$scannerId': typeof RepositoriesRepositoryIdScannersScannerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scanners/': typeof ScannersIndexRoute
  '/repositories/$repositoryId/edit': typeof RepositoriesRepositoryIdEditRoute
  '/repositories/$repositoryId/knowledge': typeof RepositoriesRepositoryIdKnowledgeRoute
  '/repositories/$repositoryId/': typeof RepositoriesRepositoryIdIndexRoute
  '/repositories/$repositoryId/scanners/$scannerId': typeof RepositoriesRepositoryIdScannersScannerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/repositories/new'
    | '/scans/$scanId'
    | '/scanners/'
    | '/repositories/$repositoryId/edit'
    | '/repositories/$repositoryId/knowledge'
    | '/repositories/$repositoryId/'
    | '/repositories/$repositoryId/scanners/$scannerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/repositories/new'
    | '/scans/$scanId'
    | '/scanners'
    | '/repositories/$repositoryId/edit'
    | '/repositories/$repositoryId/knowledge'
    | '/repositories/$repositoryId'
    | '/repositories/$repositoryId/scanners/$scannerId'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/repositories/new'
    | '/scans/$scanId'
    | '/scanners/'
    | '/repositories/$repositoryId/edit'
    | '/repositories/$repositoryId/knowledge'
    | '/repositories/$repositoryId/'
    | '/repositories/$repositoryId/scanners/$scannerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  RepositoriesNewRoute: typeof RepositoriesNewRoute
  ScansScanIdRoute: typeof ScansScanIdRoute
  ScannersIndexRoute: typeof ScannersIndexRoute
  RepositoriesRepositoryIdEditRoute: typeof RepositoriesRepositoryIdEditRoute
  RepositoriesRepositoryIdKnowledgeRoute: typeof RepositoriesRepositoryIdKnowledgeRoute
  RepositoriesRepositoryIdIndexRoute: typeof RepositoriesRepositoryIdIndexRoute
  RepositoriesRepositoryIdScannersScannerIdRoute: typeof RepositoriesRepositoryIdScannersScannerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/new': {
      id: '/repositories/new'
      path: '/repositories/new'
      fullPath: '/repositories/new'
      preLoaderRoute: typeof RepositoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanners/': {
      id: '/scanners/'
      path: '/scanners'
      fullPath: '/scanners/'
      preLoaderRoute: typeof ScannersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$scanId': {
      id: '/scans/$scanId'
      path: '/scans/$scanId'
      fullPath: '/scans/$scanId'
      preLoaderRoute: typeof ScansScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/': {
      id: '/repositories/$repositoryId/'
      path: '/repositories/$repositoryId'
      fullPath: '/repositories/$repositoryId/'
      preLoaderRoute: typeof RepositoriesRepositoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/edit': {
      id: '/repositories/$repositoryId/edit'
      path: '/repositories/$repositoryId/edit'
      fullPath: '/repositories/$repositoryId/edit'
      preLoaderRoute: typeof RepositoriesRepositoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/knowledge': {
      id: '/repositories/$repositoryId/knowledge'
      path: '/repositories/$repositoryId/knowledge'
      fullPath: '/repositories/$repositoryId/knowledge'
      preLoaderRoute: typeof RepositoriesRepositoryIdKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/scanners/$scannerId': {
      id: '/repositories/$repositoryId/scanners/$scannerId'
      path: '/repositories/$repositoryId/scanners/$scannerId'
      fullPath: '/repositories/$repositoryId/scanners/$scannerId'
      preLoaderRoute: typeof RepositoriesRepositoryIdScannersScannerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  RepositoriesNewRoute: RepositoriesNewRoute,
  ScansScanIdRoute: ScansScanIdRoute,
  ScannersIndexRoute: ScannersIndexRoute,
  RepositoriesRepositoryIdEditRoute: RepositoriesRepositoryIdEditRoute,
  RepositoriesRepositoryIdKnowledgeRoute:
    RepositoriesRepositoryIdKnowledgeRoute,
  RepositoriesRepositoryIdIndexRoute: RepositoriesRepositoryIdIndexRoute,
  RepositoriesRepositoryIdScannersScannerIdRoute:
    RepositoriesRepositoryIdScannersScannerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
