/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ScannersIndexRouteImport } from './routes/scanners/index'
import { Route as ScansIndexRouteImport } from './routes/scans/index'
import { Route as RepositoriesRepositoryIdIndexRouteImport } from './routes/repositories/$repositoryId/index'
import { Route as RepositoriesNewIndexRouteImport } from './routes/repositories/new/index'
import { Route as ScansScanIdIndexRouteImport } from './routes/scans/$scanId/index'
import { Route as ApiPatchesPatchIdIndexRouteImport } from './routes/api/patches/$patchId/index'
import { Route as ApiWebhooksGithubIndexRouteImport } from './routes/api/webhooks/github/index'
import { Route as RepositoriesRepositoryIdEditIndexRouteImport } from './routes/repositories/$repositoryId/edit/index'
import { Route as RepositoriesRepositoryIdKnowledgeIndexRouteImport } from './routes/repositories/$repositoryId/knowledge/index'
import { Route as RepositoriesRepositoryIdSecurityIndexRouteImport } from './routes/repositories/$repositoryId/security/index'
import { Route as RepositoriesRepositoryIdScannersScannerIdIndexRouteImport } from './routes/repositories/$repositoryId/scanners/$scannerId/index'
import { Route as ApiScansScanIdArtifactsKindIndexRouteImport } from './routes/api/scans/$scanId/artifacts/$kind/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannersIndexRoute = ScannersIndexRouteImport.update({
  id: '/scanners/',
  path: '/scanners/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansIndexRoute = ScansIndexRouteImport.update({
  id: '/scans/',
  path: '/scans/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRepositoryIdIndexRoute =
  RepositoriesRepositoryIdIndexRouteImport.update({
    id: '/repositories/$repositoryId/',
    path: '/repositories/$repositoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoriesNewIndexRoute = RepositoriesNewIndexRouteImport.update({
  id: '/repositories/new/',
  path: '/repositories/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansScanIdIndexRoute = ScansScanIdIndexRouteImport.update({
  id: '/scans/$scanId/',
  path: '/scans/$scanId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatchesPatchIdIndexRoute = ApiPatchesPatchIdIndexRouteImport.update({
  id: '/api/patches/$patchId/',
  path: '/api/patches/$patchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGithubIndexRoute = ApiWebhooksGithubIndexRouteImport.update({
  id: '/api/webhooks/github/',
  path: '/api/webhooks/github/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRepositoryIdEditIndexRoute =
  RepositoriesRepositoryIdEditIndexRouteImport.update({
    id: '/repositories/$repositoryId/edit/',
    path: '/repositories/$repositoryId/edit/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoriesRepositoryIdKnowledgeIndexRoute =
  RepositoriesRepositoryIdKnowledgeIndexRouteImport.update({
    id: '/repositories/$repositoryId/knowledge/',
    path: '/repositories/$repositoryId/knowledge/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoriesRepositoryIdSecurityIndexRoute =
  RepositoriesRepositoryIdSecurityIndexRouteImport.update({
    id: '/repositories/$repositoryId/security/',
    path: '/repositories/$repositoryId/security/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoriesRepositoryIdScannersScannerIdIndexRoute =
  RepositoriesRepositoryIdScannersScannerIdIndexRouteImport.update({
    id: '/repositories/$repositoryId/scanners/$scannerId/',
    path: '/repositories/$repositoryId/scanners/$scannerId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScansScanIdArtifactsKindIndexRoute =
  ApiScansScanIdArtifactsKindIndexRouteImport.update({
    id: '/api/scans/$scanId/artifacts/$kind/',
    path: '/api/scans/$scanId/artifacts/$kind/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/scanners/': typeof ScannersIndexRoute
  '/scans/': typeof ScansIndexRoute
  '/repositories/$repositoryId/': typeof RepositoriesRepositoryIdIndexRoute
  '/repositories/new/': typeof RepositoriesNewIndexRoute
  '/scans/$scanId/': typeof ScansScanIdIndexRoute
  '/api/patches/$patchId/': typeof ApiPatchesPatchIdIndexRoute
  '/api/webhooks/github/': typeof ApiWebhooksGithubIndexRoute
  '/repositories/$repositoryId/edit/': typeof RepositoriesRepositoryIdEditIndexRoute
  '/repositories/$repositoryId/knowledge/': typeof RepositoriesRepositoryIdKnowledgeIndexRoute
  '/repositories/$repositoryId/security/': typeof RepositoriesRepositoryIdSecurityIndexRoute
  '/repositories/$repositoryId/scanners/$scannerId/': typeof RepositoriesRepositoryIdScannersScannerIdIndexRoute
  '/api/scans/$scanId/artifacts/$kind/': typeof ApiScansScanIdArtifactsKindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/scanners': typeof ScannersIndexRoute
  '/scans': typeof ScansIndexRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdIndexRoute
  '/repositories/new': typeof RepositoriesNewIndexRoute
  '/scans/$scanId': typeof ScansScanIdIndexRoute
  '/api/patches/$patchId': typeof ApiPatchesPatchIdIndexRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubIndexRoute
  '/repositories/$repositoryId/edit': typeof RepositoriesRepositoryIdEditIndexRoute
  '/repositories/$repositoryId/knowledge': typeof RepositoriesRepositoryIdKnowledgeIndexRoute
  '/repositories/$repositoryId/security': typeof RepositoriesRepositoryIdSecurityIndexRoute
  '/repositories/$repositoryId/scanners/$scannerId': typeof RepositoriesRepositoryIdScannersScannerIdIndexRoute
  '/api/scans/$scanId/artifacts/$kind': typeof ApiScansScanIdArtifactsKindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/scanners/': typeof ScannersIndexRoute
  '/scans/': typeof ScansIndexRoute
  '/repositories/$repositoryId/': typeof RepositoriesRepositoryIdIndexRoute
  '/repositories/new/': typeof RepositoriesNewIndexRoute
  '/scans/$scanId/': typeof ScansScanIdIndexRoute
  '/api/patches/$patchId/': typeof ApiPatchesPatchIdIndexRoute
  '/api/webhooks/github/': typeof ApiWebhooksGithubIndexRoute
  '/repositories/$repositoryId/edit/': typeof RepositoriesRepositoryIdEditIndexRoute
  '/repositories/$repositoryId/knowledge/': typeof RepositoriesRepositoryIdKnowledgeIndexRoute
  '/repositories/$repositoryId/security/': typeof RepositoriesRepositoryIdSecurityIndexRoute
  '/repositories/$repositoryId/scanners/$scannerId/': typeof RepositoriesRepositoryIdScannersScannerIdIndexRoute
  '/api/scans/$scanId/artifacts/$kind/': typeof ApiScansScanIdArtifactsKindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/scanners/'
    | '/scans/'
    | '/repositories/$repositoryId/'
    | '/repositories/new/'
    | '/scans/$scanId/'
    | '/api/patches/$patchId/'
    | '/api/webhooks/github/'
    | '/repositories/$repositoryId/edit/'
    | '/repositories/$repositoryId/knowledge/'
    | '/repositories/$repositoryId/security/'
    | '/repositories/$repositoryId/scanners/$scannerId/'
    | '/api/scans/$scanId/artifacts/$kind/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/scanners'
    | '/scans'
    | '/repositories/$repositoryId'
    | '/repositories/new'
    | '/scans/$scanId'
    | '/api/patches/$patchId'
    | '/api/webhooks/github'
    | '/repositories/$repositoryId/edit'
    | '/repositories/$repositoryId/knowledge'
    | '/repositories/$repositoryId/security'
    | '/repositories/$repositoryId/scanners/$scannerId'
    | '/api/scans/$scanId/artifacts/$kind'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/scanners/'
    | '/scans/'
    | '/repositories/$repositoryId/'
    | '/repositories/new/'
    | '/scans/$scanId/'
    | '/api/patches/$patchId/'
    | '/api/webhooks/github/'
    | '/repositories/$repositoryId/edit/'
    | '/repositories/$repositoryId/knowledge/'
    | '/repositories/$repositoryId/security/'
    | '/repositories/$repositoryId/scanners/$scannerId/'
    | '/api/scans/$scanId/artifacts/$kind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ScannersIndexRoute: typeof ScannersIndexRoute
  ScansIndexRoute: typeof ScansIndexRoute
  RepositoriesRepositoryIdIndexRoute: typeof RepositoriesRepositoryIdIndexRoute
  RepositoriesNewIndexRoute: typeof RepositoriesNewIndexRoute
  ScansScanIdIndexRoute: typeof ScansScanIdIndexRoute
  ApiPatchesPatchIdIndexRoute: typeof ApiPatchesPatchIdIndexRoute
  ApiWebhooksGithubIndexRoute: typeof ApiWebhooksGithubIndexRoute
  RepositoriesRepositoryIdEditIndexRoute: typeof RepositoriesRepositoryIdEditIndexRoute
  RepositoriesRepositoryIdKnowledgeIndexRoute: typeof RepositoriesRepositoryIdKnowledgeIndexRoute
  RepositoriesRepositoryIdSecurityIndexRoute: typeof RepositoriesRepositoryIdSecurityIndexRoute
  RepositoriesRepositoryIdScannersScannerIdIndexRoute: typeof RepositoriesRepositoryIdScannersScannerIdIndexRoute
  ApiScansScanIdArtifactsKindIndexRoute: typeof ApiScansScanIdArtifactsKindIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanners/': {
      id: '/scanners/'
      path: '/scanners'
      fullPath: '/scanners/'
      preLoaderRoute: typeof ScannersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/': {
      id: '/scans/'
      path: '/scans'
      fullPath: '/scans/'
      preLoaderRoute: typeof ScansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/': {
      id: '/repositories/$repositoryId/'
      path: '/repositories/$repositoryId'
      fullPath: '/repositories/$repositoryId/'
      preLoaderRoute: typeof RepositoriesRepositoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/new/': {
      id: '/repositories/new/'
      path: '/repositories/new'
      fullPath: '/repositories/new/'
      preLoaderRoute: typeof RepositoriesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$scanId/': {
      id: '/scans/$scanId/'
      path: '/scans/$scanId'
      fullPath: '/scans/$scanId/'
      preLoaderRoute: typeof ScansScanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patches/$patchId/': {
      id: '/api/patches/$patchId/'
      path: '/api/patches/$patchId'
      fullPath: '/api/patches/$patchId/'
      preLoaderRoute: typeof ApiPatchesPatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github/': {
      id: '/api/webhooks/github/'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github/'
      preLoaderRoute: typeof ApiWebhooksGithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/edit/': {
      id: '/repositories/$repositoryId/edit/'
      path: '/repositories/$repositoryId/edit'
      fullPath: '/repositories/$repositoryId/edit/'
      preLoaderRoute: typeof RepositoriesRepositoryIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/knowledge/': {
      id: '/repositories/$repositoryId/knowledge/'
      path: '/repositories/$repositoryId/knowledge'
      fullPath: '/repositories/$repositoryId/knowledge/'
      preLoaderRoute: typeof RepositoriesRepositoryIdKnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/security/': {
      id: '/repositories/$repositoryId/security/'
      path: '/repositories/$repositoryId/security'
      fullPath: '/repositories/$repositoryId/security/'
      preLoaderRoute: typeof RepositoriesRepositoryIdSecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/scanners/$scannerId/': {
      id: '/repositories/$repositoryId/scanners/$scannerId/'
      path: '/repositories/$repositoryId/scanners/$scannerId'
      fullPath: '/repositories/$repositoryId/scanners/$scannerId/'
      preLoaderRoute: typeof RepositoriesRepositoryIdScannersScannerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scans/$scanId/artifacts/$kind/': {
      id: '/api/scans/$scanId/artifacts/$kind/'
      path: '/api/scans/$scanId/artifacts/$kind'
      fullPath: '/api/scans/$scanId/artifacts/$kind/'
      preLoaderRoute: typeof ApiScansScanIdArtifactsKindIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ScannersIndexRoute: ScannersIndexRoute,
  ScansIndexRoute: ScansIndexRoute,
  RepositoriesRepositoryIdIndexRoute: RepositoriesRepositoryIdIndexRoute,
  RepositoriesNewIndexRoute: RepositoriesNewIndexRoute,
  ScansScanIdIndexRoute: ScansScanIdIndexRoute,
  ApiPatchesPatchIdIndexRoute: ApiPatchesPatchIdIndexRoute,
  ApiWebhooksGithubIndexRoute: ApiWebhooksGithubIndexRoute,
  RepositoriesRepositoryIdEditIndexRoute:
    RepositoriesRepositoryIdEditIndexRoute,
  RepositoriesRepositoryIdKnowledgeIndexRoute:
    RepositoriesRepositoryIdKnowledgeIndexRoute,
  RepositoriesRepositoryIdSecurityIndexRoute:
    RepositoriesRepositoryIdSecurityIndexRoute,
  RepositoriesRepositoryIdScannersScannerIdIndexRoute:
    RepositoriesRepositoryIdScannersScannerIdIndexRoute,
  ApiScansScanIdArtifactsKindIndexRoute: ApiScansScanIdArtifactsKindIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
